# Homepage
base_url = "https://anubhavp.dev/zuzu/"

# template
template = "fuzzymfx"

# Path to the directory containing the content
source_dir = "content"

# Path to the directory containing the output
output_dir = "docs"

# Path to the directory containing the templates
template_dir = "templates/fuzzymfx"

# Path to the directory containing the static files
static_dir = "static"

# Theme
templateHTML = "templates/fuzzymfx/template.html"

# Json
json_dir = "templates/initial/static"

# search
search = false

# title of blog
title = "Zuzu"

# author
author = "Anubhab Patnaik"

# description
description = "A space for my two cents, musings, and insights."